baseURL = "http://croixdechartreuse.mildred.fr/"
languageCode = "fr-fr"
title = "Croix et petits monuments de Chartreuse"
#theme = "croix-de-chartreuse"
#theme = "croix-de-chartreuse"

[taxonomies]
  categorie = "categories"
  lieu      = "lieux"

[menu]

  [[menu.main]]
    identifier = "accueil"
    name       = "Accueil"
    title      = ""
    url        = "/"
    weight     = -120

  [[menu.main]]
    identifier = "asso"
    name       = "L'association"
    title      = ""
    url        = "/asso/"
    weight     = -110

  [[menu.main]]
    identifier = "fiches"
    name       = "Fiches"
    title      = ""
    url        = "/fiches/"
    weight     = -100

[Params]
  # Add staticman API URL to enable staticman comments
  staticman_api = "https://staticman-mildred.nfshost.com/v2/entry/mildred/croix-de-chartreuse/master/comments"
  comments = true
